### PR TITLE
fix: links in header when on CoC

### PR DESCRIPTION
**Pull request by posva**
Fix the links on the header when we are not on the root page

### CODE REVIEW

**Comment by aarongarciah** [comment]
Thank you! My bad 😅

**Comment by posva** [comment]
That was fast 😆 
I love the design and simplicity of the website

**Comment by aarongarciah** [comment]
Thank you! That was my intention building the website. I was afraid that people thought that the simplicity wasn't intentional 😬

**Comment by posva** [comment]
It has everything it needs 👌

**Pull request merged**
